name: Lint

on: push

jobs:
  run-backend-linters:
    name: Run backend linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run Pylint
        working-directory: backend
        run: pylint api
  
      - name: Run Black
        working-directory: backend
        run: black . --check