name: Lint

on: push

jobs:
  run-backend-unit-tests:
    name: Run backend unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install -r requirements.txt
        working-directory: backend

      - name: Run unit tests
        working-directory: backend/api
        run: pytest
  